In [3]:
from datetime import timedelta
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from google.colab import auth
from google.cloud import bigquery, storage

# Authenticate and set up environment
auth.authenticate_user()
project_id = 'mcxrp-429811'
os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
!gcloud config set project {project_id}

# Initialize BigQuery client
client = bigquery.Client(project=project_id)

# Initialize GCP Storage client with user_project parameter
storage_client = storage.Client(project=project_id)
bucket_name = 'cxr_embedding'
bucket = storage_client.bucket(bucket_name, user_project=project_id)

# Path to the data in your GCP bucket
data_path = 'image-embeddings-mimic-cxr-1.0.physionet.org/files'

# Query BigQuery to get required columns
query = """
SELECT study.study_id, study.subject_id, study.study_datetime, study.path, record_list.dicom_id
FROM `physionet-data.mimic_cxr.study` AS study
JOIN `physionet-data.mimic_cxr.record_list` AS record_list
ON study.study_id = record_list.study_id
"""
query_job = client.query(query)
bigquery_df = query_job.to_dataframe()

# Load the ARDS cohort data table from GCP bucket
ards_data_path = 'ARDS cohort ~1000 patients 28 days July.csv'
ards_blob = bucket.blob(ards_data_path)
ards_blob.download_to_filename('/tmp/ards_data.csv')
ards_df = pd.read_csv('/tmp/ards_data.csv')

# Select required columns from ARDS cohort data
ards_filtered_df = ards_df[['subject_id', 'timezero', 'icu_mort', 'avg_peep', 'days_from_start']]

# Convert time columns to datetime format
bigquery_df['study_datetime'] = pd.to_datetime(bigquery_df['study_datetime'])
ards_filtered_df['timezero'] = pd.to_datetime(ards_filtered_df['timezero'])

# Keep only the rows where subject_id is in both dataframes
merged_subject_ids = set(bigquery_df['subject_id']).intersection(set(ards_filtered_df['subject_id']))
bigquery_df = bigquery_df[bigquery_df['subject_id'].isin(merged_subject_ids)]
ards_filtered_df = ards_filtered_df[ards_filtered_df['subject_id'].isin(merged_subject_ids)]

Updated property [core/project].

<ipython-input-3-53e0eeb9a4a9>:40: DtypeWarning: Columns (41) have mixed types. Specify dtype option on import or set low_memory=False.
  ards_df = pd.read_csv('/tmp/ards_data.csv')
<ipython-input-3-53e0eeb9a4a9>:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ards_filtered_df['timezero'] = pd.to_datetime(ards_filtered_df['timezero'])

In [ ]:
# Function to load embedding vectors from GCP bucket
def load_embedding_vector(file_path, dicom_id):
    clean_path = file_path.replace('.txt', '')
    if clean_path.startswith('files/'):
        clean_path = clean_path[len('files/'):]
    file_name = dicom_id + '.tfrecord'
    full_path = os.path.join(data_path, clean_path, file_name)
    blob = bucket.blob(full_path)

    #print(f"Checking if blob exists at path: {full_path}")  # Debugging log

    if blob.exists():
        #print(f"Blob found. Downloading data from: {full_path}")  # Debugging log
        try:
            raw_data = blob.download_as_bytes()
            print(f"Raw data size: {len(raw_data)} bytes")  # Debugging log

            # Save the downloaded data to a temporary file for TensorFlow to read
            temp_file_path = '/tmp/temp.tfrecord'
            with open(temp_file_path, 'wb') as f:
                f.write(raw_data)

            raw_dataset = tf.data.TFRecordDataset(temp_file_path)
            for raw_record in raw_dataset.take(1):
                example = tf.train.Example()
                example.ParseFromString(raw_record.numpy())
                embedding = example.features.feature['embedding'].float_list.value
                return embedding
        except tf.errors.DataLossError as e:
            print(f"Data loss error reading TFRecord file {full_path}: {e}")
        except tf.errors.InvalidArgumentError as e:
            print(f"Invalid argument error reading TFRecord file {full_path}: {e}")
        except Exception as e:
            print(f"General error reading TFRecord file {full_path}: {e}")
    else:
        print(f"File {full_path} does not exist")
    return None

# Create a new DataFrame to hold valid records
valid_rows = []

# Load embeddings into the DataFrame
for index, row in bigquery_df.iterrows():
    path = row['path']
    dicom_id = row['dicom_id']
    embedding = load_embedding_vector(path, dicom_id)
    if embedding:
        for i, val in enumerate(embedding):
            row[f'embedding_{i}'] = val
        valid_rows.append(row)

# Create a new DataFrame from valid rows
valid_df = pd.DataFrame(valid_rows)

# Merge the two dataframes on subject_id
merged_df = pd.merge(valid_df, ards_filtered_df, on='subject_id', how='inner')

# **Calculate the time difference between study_datetime and timezero**
merged_df['time_diff'] = merged_df['study_datetime'] - merged_df['timezero']

# **Filter out rows where the study_date_time is within 2 days before or within 1 day after the timezero**
filtered_df = merged_df[(merged_df['time_diff'] < -timedelta(days=2)) | (merged_df['time_diff'] > timedelta(days=1))]

# Sort by subject_id and time_diff, then drop duplicates keeping the closest study
#merged_df = merged_df.sort_values(by=['subject_id', 'time_diff']).drop_duplicates(subset='subject_id', keep='first')

# Reorder columns to have the embedding columns at the end
embedding_columns = [col for col in merged_df.columns if col.startswith('embedding_')]
non_embedding_columns = [col for col in merged_df.columns if not col.startswith('embedding_')]

final_columns = non_embedding_columns + embedding_columns
final_df = merged_df[final_columns]

# Save the final DataFrame to a CSV file in the GCP bucket
final_combined_data_path = 'final_combined_data1.csv'
final_combined_blob = bucket.blob(final_combined_data_path)
final_combined_blob.upload_from_string(final_df.to_csv(index=False), 'text/csv')
print(f"Final combined data saved to {final_combined_data_path} in GCP bucket")

Streaming output truncated to the last 5000 lines.
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p12/p12691278/s51273308/9c081861-9bf48f61-7fb8881c-47299e0f-8ea2b5fe.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s51261465/6f70067b-d8bfc03e-42991465-de757fd6-32f37e2a.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s55198278/25228e0b-4be68d6c-16f6ed4e-39c6fc9b-45a78512.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s56312875/51586257-0ef09a11-b2125648-5347e563-2f2c995d.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s57734656/469418b1-eab246ab-b3f3ed51-b819ba8c-bb343fc1.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s58663433/5eeb72c6-c3d5748f-2bd8acef-1dee9e53-dfd80bb2.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s50466391/650308b5-db81edb5-30adb2f2-d993cffc-b462515e.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s51332346/1ad11298-ac5f288c-8900aa8d-24153568-339a50d0.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s51409546/f5320a9d-03199cf9-fffe007c-f1016cc4-97e03900.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s51670609/8abed151-2fb16852-45e3d439-8b2004ef-6bb82ec0.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s53411620/d9787136-8dfacb39-5cf1c8c5-5b03b981-4f0aefb3.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s55203687/3810a450-8af51367-b702a3ce-b436975e-6a485b90.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s55254839/84803f43-9acbf6be-56ae58f1-0b41ec8d-dd7c0030.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13598803/s57702265/4cd8f982-9626bf6c-121ad675-13b40157-929fbadf.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p10/p10978131/s57096663/8d191623-0a83d9df-3482cace-355dfc73-6544355f.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p10/p10978131/s52567726/342440c7-94578784-e9c1c609-ad669026-9c4416c9.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p19/p19507539/s54563220/e42a3c14-4367d43c-7ad6fca0-3d2f8c88-f63c8940.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p10/p10955604/s50509154/616b57b0-ff9e47fd-0d7f765d-56a5a4d1-52ba03dc.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p10/p10955604/s50954526/8a809389-9a1026ce-887cc2c1-b23d452c-995b9ca2.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p10/p10955604/s51224963/5d50a9fd-f3afdc26-22de2098-1ed2cf2b-ccd60a24.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p11/p11109975/s51247409/76f31427-f136aaaa-24b837de-76076984-dca3ff16.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53045859/9da0b743-32e67cdb-d26a27bb-9841d3a8-ff08bcdb.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53420046/34f1d7ed-42916f4a-68124202-1edd011a-aa26db56.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s54399638/216ae93f-46661602-2170a65e-bc27129a-eae0aca9.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s56696064/fc70e097-ea7913b6-820e3327-bd6470e0-01a29aa8.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s57589679/f29aef88-e53ddae6-8740d2ae-4de09db8-6713ce94.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s57589679/fb12c9e2-9b36d40e-57fb22e7-11eef4a3-0e73512d.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s58980708/e8f4bf8c-45e65658-9c4c09a1-b06aec12-f9d66a30.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s51298911/9152a4aa-38fb1e54-c55b03bf-832b55dd-ce1670c7.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s51298911/f9840a87-17d9ee1a-4c6813f8-7c3297ba-c262477b.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s51451093/55047be4-928ee013-b38b8865-bd3fdc7a-4690c6af.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s51451093/94bf8c57-42c15523-b83433b1-fc846ff5-b58d120e.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53045859/51eed3c5-511c6625-adab9aec-72e2d57c-9628013c.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53420046/d7a477c0-054dc480-77a5550a-2a314a44-c0bade78.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53672820/6dcc8603-bdb1aac7-aaada083-d9d1f2db-37d4aeee.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s53672820/c95aad25-d1be7d42-2d43b19f-6896974f-e1743a6f.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s54227580/112dcfdf-48fef428-87c262a0-d3fb1223-8e9bb909.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s56160462/3e10b799-5c19610c-f6ef8ce0-c8d3ec64-f3c69a15.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s56696064/ed6c5ef0-eb4df1ae-d926c008-e016eb0b-641e9f96.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s57589679/5243c28e-34e2109a-6bdf4cc1-a9100624-b96f1743.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13325402/s58980708/edd1c04e-11d6fd58-bb88a5bd-8b89f317-cb5090bc.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p12/p12620123/s53183002/0857ac44-5e47624f-89ed33f0-1c611c9d-2aadd22d.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s51179137/da4dd3bf-e3c3cef6-c2932712-4ea1868f-bb49a679.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s51885741/2713f97c-434c94c1-0eebc5f0-2a6dcfeb-a00f8ae4.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s52300742/7c577fdd-cf2ca741-20f15f2e-fa65158c-4bfe3e44.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s58095046/7c58d5dc-b27b0ba2-f4f04a1f-eda0529a-174d4c14.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s51179137/f944ee60-4f141df4-e127ff69-017b2647-964dcbe0.tfrecord does not exist
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s51885741/b6bb5a72-ba249ae7-b524fdac-2d6f09d1-fa75948c.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s54544721/64b0701c-df0213c5-4b04dacb-d41dcbc8-01d7d5f2.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p13/p13247581/s58095046/e0e37d0a-5974ee39-fd808fad-ad6612ef-5ff6d7db.tfrecord does not exist
Raw data size: 5698 bytes
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p17/p17125981/s50945509/af671a77-9d26b2ee-3bbbb893-84ea8ef4-ea2b6d97.tfrecord does not exist
Raw data size: 5698 bytes
File image-embeddings-mimic-cxr-1.0.physionet.org/files/p17/p17125981/s52041440/b573bcf4-a494d966-fc93f7cd-21788044-1b739083.tfrecord does not exist
Raw data size: 5698 bytes

In [ ]:
auth.authenticate_user()
project_id = 'mcxrp-429811'  # Replace with your actual project ID
os.environ["GOOGLE_CLOUD_PROJECT"] = project_id

# Initialize BigQuery client
client = bigquery.Client(project=project_id)

# Mount Google Drive
drive.mount('/content/drive')

# Load the extracted columns CSV file
extracted_columns_path = '/content/drive/My Drive/colab_data/extracted_columns.csv'
extracted_df = pd.read_csv(extracted_columns_path)

In [ ]:
dataset_id = 'mcxrp-429811.mimic_cxr1'  # Replace with your valid dataset ID
dataset = bigquery.Dataset(dataset_id)
dataset.location = "US"

In [ ]:
# Create the dataset
try:
    client.create_dataset(dataset)  # API request
    print(f"Created dataset {dataset_id}")
except Exception as e:
    print(f"Dataset {dataset_id} already exists or there was an error: {e}")

Created dataset mcxrp-429811.mimic_cxr1

In [ ]:
# Verify dataset and table names
dataset_id = 'mimic_cxr1'

# Query for CXR metadata from BigQuery
sql = f"""
CREATE VIEW `{dataset_id}.cxr_data` AS
SELECT * FROM `physionet-data.mimic_cxr.record_list`
"""
# Run the query and load the result into a DataFrame
try:
    client.query(sql).result()
    print(f"View cxr_data created successfully in dataset {dataset_id}")
except Exception as e:
    print(f"Error creating view: {e}")

View age1000 created successfully in dataset mimic_cxr1

In [ ]:
# Query the created view to load into a DataFrame
view_query = f"""
SELECT * FROM `{dataset_id}.cxr_data`
"""

# Run the query and load the result into a DataFrame
try:
    df_view = client.query(view_query).to_dataframe()
    # Display the resulting DataFrame
    display(df_view)
except Exception as e:
    print(f"Error querying view: {e}")

,subject_id,study_id,dicom_id,path
0,18415616,58605705,75d67482-46fbfcfb-b9d3be10-98f1b1dd-ba9748dc,files/p18/p18415616/s58605705/75d67482-46fbfcf...
1,18415616,58605705,91ea24c1-ddf8f918-0c579885-c0bf36ed-3a2b306a,files/p18/p18415616/s58605705/91ea24c1-ddf8f91...
2,19136768,50193341,69ea47d2-8e44c7ea-8fd5dada-9385460a-fd8863d2,files/p19/p19136768/s50193341/69ea47d2-8e44c7e...
3,19136768,58264435,c2822cd9-785880dd-b21df2f4-feae6873-a3dbcc34,files/p19/p19136768/s58264435/c2822cd9-785880d...
4,19136768,50193341,cbc8f5b5-f0eb7c26-5f128cde-62af96cb-9dd4f92a,files/p19/p19136768/s50193341/cbc8f5b5-f0eb7c2...
...,...,...,...,...
377105,17956863,54433918,766f17e3-6064ab91-59626504-e0570e87-d6e63c64,files/p17/p17956863/s54433918/766f17e3-6064ab9...
377106,17956863,54433918,a21b3a0b-fb10071c-0ab33ae4-0406b28b-a2e42bc3,files/p17/p17956863/s54433918/a21b3a0b-fb10071...
377107,17956863,58645749,4baead16-4c878e7c-fcc6071d-e06ebfb2-61d25c4c,files/p17/p17956863/s58645749/4baead16-4c878e7...
377108,17956863,50736896,328fba1d-fb7a2246-f361ecc5-09c96079-48a89f06,files/p17/p17956863/s50736896/328fba1d-fb7a224...
377109,17956863,58645749,59218cf7-f2c291c7-25ed5f1f-1a839972-c93bb3b3,files/p17/p17956863/s58645749/59218cf7-f2c291c...

In [ ]:
if not extracted_df.empty and not df_view.empty:
    # Perform an inner join on 'subject_id' to get only matching records
    merged_df = pd.merge(extracted_df, df_view, on='subject_id', how='inner')
    # Display the resulting DataFrame
    display(merged_df)
else:
    print("One or both DataFrames are empty. Cannot perform merge.")

,subject_id,hadm_id,stay_id,timezero,icu_intime,icu_outtime,icu_mort,study_id,dicom_id,path
0,12595991,25205720,30027612,03/11/2147 17:38,03/11/2147 09:23,06/11/2147 19:25,1,50291999,09a7bc78-861b7d8a-bf31a633-67e32681-cec68e43,files/p12/p12595991/s50291999/09a7bc78-861b7d8...
1,12595991,25205720,30027612,03/11/2147 17:38,03/11/2147 09:23,06/11/2147 19:25,1,51474707,2fe309ca-e58c4d80-6f0002e9-cd535709-1c3f5890,files/p12/p12595991/s51474707/2fe309ca-e58c4d8...
2,12595991,25205720,30027612,03/11/2147 17:38,03/11/2147 09:23,06/11/2147 19:25,1,52076561,bd31fe67-ad4d5454-2cfd7c09-13c04383-d38297ac,files/p12/p12595991/s52076561/bd31fe67-ad4d545...
3,12595991,25205720,30027612,03/11/2147 17:38,03/11/2147 09:23,06/11/2147 19:25,1,55463602,bf9f8403-f941bbb9-13c134ff-ac80d6b9-e8442bdf,files/p12/p12595991/s55463602/bf9f8403-f941bbb...
4,12595991,25205720,30027612,03/11/2147 17:38,03/11/2147 09:23,06/11/2147 19:25,1,58585557,036272e9-9052e7c2-444e59fd-86a7f36d-9dfe191a,files/p12/p12595991/s58585557/036272e9-9052e7c...
...,...,...,...,...,...,...,...,...,...,...
11075,19046950,24352151,39998622,11/02/2135 22:15,11/02/2135 18:13,20/02/2135 17:53,0,57521020,ee407622-9577fed7-b1ddfa12-135f0f30-d9e9d6c1,files/p19/p19046950/s57521020/ee407622-9577fed...
11076,19046950,24352151,39998622,11/02/2135 22:15,11/02/2135 18:13,20/02/2135 17:53,0,59040853,da90fc30-f83bad51-67e557a8-86347b63-59b81b61,files/p19/p19046950/s59040853/da90fc30-f83bad5...
11077,19046950,24352151,39998622,11/02/2135 22:15,11/02/2135 18:13,20/02/2135 17:53,0,59568069,1668fc3c-a77bbd7a-83e11d91-10d68655-0466d48f,files/p19/p19046950/s59568069/1668fc3c-a77bbd7...
11078,19046950,24352151,39998622,11/02/2135 22:15,11/02/2135 18:13,20/02/2135 17:53,0,59642006,87094dfc-4dc02c35-932c18be-da0f9ee3-3b4ae3c1,files/p19/p19046950/s59642006/87094dfc-4dc02c3...
11079,19046950,24352151,39998622,11/02/2135 22:15,11/02/2135 18:13,20/02/2135 17:53,0,59750727,8a0ddc14-a80a6626-7417d628-186808b7-7a672444,files/p19/p19046950/s59750727/8a0ddc14-a80a662...

In [ ]:
# If you want to save the resulting DataFrame to a CSV file
output_path = '/content/drive/My Drive/colab_data/merged_patient_data.csv'
merged_df.to_csv(output_path, index=False)
print(f"Merged patient data saved to {output_path}")
############################################################################################################

Merged patient data saved to /content/drive/My Drive/colab_data/merged_patient_data.csv

In [ ]:
!pip install google-auth google-auth-oauthlib google-auth-httplib2 google-cloud-storage

Requirement already satisfied: google-auth in /usr/local/lib/python3.10/dist-packages (2.27.0)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.10/dist-packages (1.2.1)
Requirement already satisfied: google-auth-httplib2 in /usr/local/lib/python3.10/dist-packages (0.1.1)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.10/dist-packages (2.8.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth) (5.4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib) (1.3.1)
Requirement already satisfied: httplib2>=0.19.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-httplib2) (0.22.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.16.2)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.3.3)
Requirement already satisfied: google-resumable-media>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.7.1)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage) (2.31.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage) (1.63.2)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage) (3.20.3)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media>=2.3.2->google-cloud-storage) (1.5.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.10/dist-packages (from httplib2>=0.19.0->google-auth-httplib2) (3.1.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2024.7.4)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.2.2)